name: AudioHaptics
options:
  bundleIdPrefix: com.example
  deploymentTarget:
    iOS: "15.0"

targets:
  AudioHaptics:
    type: application
    platform: iOS
    sources:
      - path: AudioHaptics
    resources:
      - path: Resources
    info:
      path: Resources/Info.plist
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.example.AudioHaptics
        SWIFT_VERSION: 5.0
        TARGETED_DEVICE_FAMILY: "1"
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: 1.0.0
